### ISSUE TITLE
corridor systemd services hang during corridor upgrades

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#32] opened 2016-07-31 22:04 UTC
These are issues that have [happened](https://phabricator.whonix.org/T524#9666). These could happen if Tor's control protocol is not reachable / not properly set up or if Tor is not running (yet).

```
25 debian corridor-data[1917]: /usr/sbin/corridor-data: 39: /usr/sbin/corridor-data: cannot open /var/run/tor/control.authcookie: No such file

25 debian corridor-data[1917]: :25 socat[1923] E connect(5, AF=1 "/var/run/tor/control", 22): No such file or directory

52 debian corridor-data[1917]: 515 Authentication failed: Wrong length on authentication cookie.

53 debian corridor-data[1917]: :53 socat[3031] E write(1, 0x2551aa0, 7963): Broken pipe
```

As a follow up issue, it looks like corridor systemd services hang during corridor upgrades / therefore break the package management.

**Comment by rustybird** [comment] 2016-08-01 07:28
The log lines are basically a duplicate of #30, see the explanation there.

> As a follow up issue, it looks like corridor systemd services hang during corridor upgrades / therefore break the package management.

Sounds like corridor-init-logged.service needs to depend on and/or be ordered after corridor-data.service

**Closed** 2016-08-03 12:13 UTC
