### ISSUE TITLE
corridor config in /usr/local [/rw] ignored

### ISSUE THREAD

**Issue by adrelanos** [rustybird/corridor#31] opened 2016-07-31 19:41 UTC
`corridor-load-config` is used by:

* `corridor-data`
* `corridor-init-logged`
* `corridor-init-snat`

These should start after `qubes-mount-dirs.service` because `corridor-load-config`will source `/usr/local/etc/corridor.d`.

`sudo journalctl -b` reveals, that is currently not the case. Startup of `corridor-ini-forwarding` and `mount-dirs.sh` happens simultaneously.

So, all of:

* `corridor-data.service`
* `corridor-init-logged.service`
* `corridor-init-snat.service`

probably should use `After=qubes-sysinit.service` or more generically, `After=sysinit.target`. Or perhaps `After=local-fs.target`.

Related:
https://github.com/QubesOS/qubes-issues/issues/2194

**Comment by rustybird** [comment] 2016-08-01 07:00
> corridor-load-config is used by:
>
> - corridor-data
> - corridor-init-logged
> - corridor-init-snat
> 
> These should start after qubes-mount-dirs.service because corridor-load-configwill source /usr/local/etc/corridor.d.

https://github.com/rustybird/corridor/blob/master/qubes/systemd/corridor-data.service.d/qubes.conf#L2
https://github.com/rustybird/corridor/blob/master/qubes/systemd/corridor-init-logged.service.d/qubes.conf#L2
https://github.com/rustybird/corridor/blob/master/qubes/systemd/corridor-init-snat.service.d/qubes.conf#L2

> sudo journalctl -b reveals, that is currently not the case. Startup of corridor-ini-forwarding and mount-dirs.sh happens simultaneously.

Can't reproduce

> probably should use After=qubes-sysinit.service or more generically, After=sysinit.target. Or perhaps After=local-fs.target.

That would be redundant with DefaultDependencies=yes.

**Comment by rustybird** [comment] 2016-08-17 12:12
Closing this, feel free to reopen if you're sure it's still an issue somehow

**Closed by rustybird** 2016-08-17 12:12 UTC
